format = " $sudo $character"
right_format = "$directory $git_branch"
command_timeout = 1000

[directory]
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1
style = "#d8c65a"
format = "[Δ]($style bold) [$path$read_only]($style)"
home_symbol = "~"
read_only = '!'
truncation_symbol = '…/'

[line_break]
disabled = true

[character]
error_symbol =              "[⊘](#d8c65a bold blink)"
success_symbol =            "[○](#d8c65a bold)"
vimcmd_symbol =             "[○](#d8c65a bold)"
vimcmd_visual_symbol =      "[○](#d8c65a bold blink)"
vimcmd_replace_symbol =     "[⊝](#d8c65a bold)"
vimcmd_replace_one_symbol = "[⊝](#d8c65a bold blink)"

[git_branch]
format = "[$symbol]($style bold) [$branch]($style)"
symbol = "Γ"
style = "#d8c65a"

[sudo]
symbol = "αω"
format = '[$symbol](#d8c65a bold blink)'
disabled = false

[python]
symbol = "Π"
format = "[$symbol]($style bold) [$virtualenv]($style)"
style = "#d8c65a"
