[line_break]
disabled = true

[character]
error_symbol =              " [⊘](#ffffff blink)"
success_symbol =            " [○](#ffffff)"
vimcmd_symbol =             " [○](#ffffff)"
vimcmd_visual_symbol =      " [○](#ffffff blink)"
vimcmd_replace_symbol =     " [⊝](#ffffff)"
vimcmd_replace_one_symbol = " [⊝](#ffffff blink)"

[git_branch]
format = "[$symbol]($style) $branch"
symbol = "Γ"
style = "#ffffff"

[cmd_duration]
disabled = true

[memory_usage]
disabled = true

[battery]
disabled = true

[username]
format = '[$user](#ffffff)'
show_always = true

[sudo]
symbol = "~"
format = '[$symbol](#ffffff)'
disabled = false

[hostname]
format = "[$symbol]($style) $hostname"
trim_at = " "
ssh_only = true
ssh_symbol = "@"
style = "#ffffff"

[package]
symbol = ".pkg"
format = '[$symbol](#ffffff) '
disabled = true

[perl]
symbol = ".pl"
format = '[$symbol](#ffffff) '
disabled = true

[php]
symbol = ".php"
format = '[$symbol](#ffffff) '
disabled = true

[pijul_channel]
symbol = "pijul"
format = '[$symbol](#ffffff) '
disabled = true

[pulumi]
symbol = ".yml"
format = '[$symbol](#ffffff) '
disabled = true

[purescript]
symbol = ".purs"
format = '[$symbol](#ffffff) '
disabled = true

[quarto]
symbol = ".qmd"
format = '[$symbol](#ffffff) '
disabled = true

[raku]
symbol = ".raku"
format = '[$symbol](#ffffff) '
disabled = true

[ruby]
symbol = ".rb"
format = '[$symbol](#ffffff) '
disabled = true

[rust]
symbol = ".rs"
format = '[$symbol](#ffffff) '
disabled = true

[scala]
symbol = ".sc"
format = '[$symbol](#ffffff) '
disabled = true

[spack]
symbol = "spack"
format = '[$symbol](#ffffff) '
disabled = true

[solidity]
symbol = ".sol"
format = '[$symbol](#ffffff) '
disabled = true

[status]
symbol = "x"

[swift]
symbol = ".swift"
format = '[$symbol](#ffffff) '
disabled = true

[typst]
symbol = "typst"
format = '[$symbol](#ffffff) '
disabled = true

[terraform]
symbol = ".tf"
format = '[$symbol](#ffffff) '
disabled = true

[zig]
symbol = ".zig"
format = '[$symbol](#ffffff) '
disabled = true

[aws]
symbol = ".aws"
format = '[$symbol](#ffffff) '
disabled = true

[azure]
symbol = ".az"
format = '[$symbol](#ffffff) '
disabled = true

[bun]
symbol = ".js"
format = '[$symbol](#ffffff) '
disabled = true

[c]
symbol = ".c"
format = '[$symbol](#ffffff) '
disabled = true

[cobol]
symbol = ".cbl"
format = '[$symbol](#ffffff) '
disabled = true

[conda]
symbol = ".conda"
format = '[$symbol](#ffffff) '
disabled = true

[crystal]
symbol = ".cr"
format = '[$symbol](#ffffff) '
disabled = true

[cmake]
symbol = ".cmake"
format = '[$symbol](#ffffff) '
disabled = true

[daml]
symbol = ".daml"
format = '[$symbol](#ffffff) '
disabled = true

[dart]
symbol = ".dart"
format = '[$symbol](#ffffff) '
disabled = true

[deno]
symbol = ".js"
format = '[$symbol](#ffffff) '
disabled = true

[dotnet]
symbol = ".net"
format = '[$symbol](#ffffff) '
disabled = true

[docker_context]
symbol = "docker "
format = '[$symbol](#ffffff) '
disabled = true

[elixir]
symbol = ".exs"
format = '[$symbol](#ffffff) '
disabled = true

[elm]
symbol = ".elm"
format = '[$symbol](#ffffff) '
disabled = true

[fennel]
symbol = ".fnl"
format = '[$symbol](#ffffff) '
disabled = true

[fossil_branch]
symbol = ".fossil"
format = '[$symbol](#ffffff) '
disabled = true

[gcloud]
symbol = ".gcp"
format = '[$symbol](#ffffff) '
disabled = true

[gleam]
symbol = ".gleam"
format = '[$symbol](#ffffff) '
disabled = true

[golang]
symbol = ".go"
format = '[$symbol](#ffffff) '
disabled = true

[gradle]
symbol = ".gradle"
format = '[$symbol](#ffffff) '
disabled = true

[guix_shell]
symbol = ".guix"
format = '[$symbol](#ffffff) '
disabled = true

[hg_branch]
symbol = ".hg"
format = '[$symbol](#ffffff) '
disabled = true

[java]
symbol = ".java"
format = '[$symbol](#ffffff) '
disabled = true

[julia]
symbol = ".jl"
format = '[$symbol](#ffffff) '
disabled = true

[kotlin]
symbol = ".kt"
format = '[$symbol](#ffffff) '
disabled = true

[lua]
symbol = ".lua"
format = '[$symbol](#ffffff) '
disabled = true

[nodejs]
symbol = ".js"
format = '[$symbol](#ffffff) '
disabled = true

[meson]
symbol = ".meson"
format = '[$symbol](#ffffff) '
disabled = true

[nats]
symbol = ".nats"
format = '[$symbol](#ffffff) '
disabled = true

[nim]
symbol = ".nim"
format = '[$symbol](#ffffff) '
disabled = true

[nix_shell]
symbol = ".nix"
format = '[$symbol](#ffffff) '
disabled = true

[ocaml]
symbol = ".ml"
format = '[$symbol](#ffffff) '
disabled = true

[opa]
symbol = ".opa"
format = '[$symbol](#ffffff) '
disabled = true

[os.symbols]
AIX = "aix"
Alpaquita = "alq"
AlmaLinux = "alma"
Alpine = "alp"
Amazon = "amz"
Android = "andr"
Arch = "rch"
Artix = "atx"
CentOS = "cent"
Debian = "deb"
DragonFly = "dfbsd"
Emscripten = "emsc"
EndeavourOS = "ndev"
Fedora = "fed"
FreeBSD = "fbsd"
Garuda = "garu"
Gentoo = "gent"
HardenedBSD = "hbsd"
Illumos = "lum"
Kali = "kali"
Linux = "lnx"
Mabox = "mbox"
Macos = "mac"
Manjaro = "mjo"
Mariner = "mrn"
MidnightBSD = "mid"
Mint = "mint"
NetBSD = "nbsd"
NixOS = "nix"
OpenBSD = "obsd"
OpenCloudOS = "ocos"
openEuler = "oeul"
openSUSE = "osuse"
OracleLinux = "orac"
Pop = "pop"
Raspbian = "rasp"
Redhat = "rhl"
RedHatEnterprise = "rhel"
RockyLinux = "rky"
Redox = "redox"
Solus = "sol"
SUSE = "suse"
Ubuntu = "ubnt"
Ultramarine = "ultm"
Unknown = "unk"
Void = "void"
Windows = "win"
