format = " $sudo$username$hostname $character"
command_timeout = 1000

right_format = """$directory $git_branch $git_status$git_metrics $python"""

[directory]
truncation_length = 15
truncate_to_repo = false
fish_style_pwd_dir_length = 1
repo_root_style = "#4e7a1c underline"
read_only_style = "#4e7a1c"
before_repo_root_style = "#4e7a1c"
style = "#4e7a1c"
format = "[$path$read_only]($style)"
repo_root_format = "[Δ]($style bold) [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($read_only_style) "
home_symbol = "~"
read_only = '!'
truncation_symbol = '…/'

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "#4e7a1c"
ahead = ">"
behind = "<"
diverged = "!"
renamed = "r"
deleted = "x"
disabled = true

[git_branch]
format = "[$symbol]($style bold) [$branch]($style)"
symbol = "Γ"
style = "#4e7a1c"

[git_metrics]
added_style = '#4e7a1c'
deleted_style = '#4e7a1c'
format = '[↑$added]($added_style)[↓$deleted]($deleted_style)'
disabled = false

[python]
symbol = "Π"
format = "[$symbol]($style bold) [$virtualenv $version]($style)"
version_format = "$major.$minor"
style = "#4e7a1c"

[line_break]
disabled = true

[character]
error_symbol =              "[⊘](#4e7a1c bold blink)"
success_symbol =            "[○](#4e7a1c bold)"
vimcmd_symbol =             "[○](#4e7a1c bold)"
vimcmd_visual_symbol =      "[○](#4e7a1c bold blink)"
vimcmd_replace_symbol =     "[⊝](#4e7a1c bold)"
vimcmd_replace_one_symbol = "[⊝](#4e7a1c bold blink)"

[username]
format = '[$user](#4e7a1c)'
show_always = true

[sudo]
symbol = "αω"
format = '[$symbol](#4e7a1c bold blink)'
disabled = false

[hostname]
format = "[$symbol]($style bold)[$hostname]($style)"
trim_at = ""
ssh_only = true
ssh_symbol = "@"
style = "#4e7a1c"

