[metadata]
name = "theme"
author = "(me)"
background = "dark"

[colors]
bg                 = "#000000" # foreground color.
fg                 = "#ffffff" # background color.
cursor             = "#8c8804"
selection          = "#5a5802"
palette_accent_1   = "#737003"
palette_accent_2   = "#695200"
palette_accent_3   = "#fce205"
palette_accent_4   = "#fdefb2"
palette_accent_5   = "#ffffe0"
gray_scale_5       = "#ededed"
gray_scale_4       = "#bbbbbb"
gray_scale_3       = "#707070"
gray_scale_2       = "#454545"
gray_scale_1       = "#2f2f2f"
alert              = "#ffdddd"
minor_alert        = "#a30000"

[colors.wezterm]
ansi_final = "#dfc98a"
bright_final = "#978942"

[colors.nvim]
lsp_inlay_hint = "#f4ab6a"
lsp_bright = "#eabd8c"

[colors.starship]
default_style = "#ffda00"
