[metadata]
name = "light"
author = "(me)"
background = "light"

[colors]
bg                 = "#ffffff" # background color.
fg                 = "#000000" # foreground color.
cursor             = "#b0ffb0" # cursor color - should stand out against both background, foreground, palette, and grayscale colors, yet be a variant of the accent or selection colors.
selection          = "#e0e8b0" # highlight/selection color, should stand out against background, foreground, and grayscale colors, yet be a different complementary color to the palette colors.
palette_accent_1   = "#f0fff0" # palette accent color closest to background.
palette_accent_2   = "#dce8dc" # palette accent color intermediate to palette_accent_1 and palette_accent_3.
palette_accent_3   = "#4a704e" # intermediary palette color directly in between palette_accent_1 (closest to background) and palette_accent_5 (closest to foreground).
palette_accent_4   = "#2a4c2a" # palette accent color intermediate to palette_accent_3 and palette_accent_5.
palette_accent_5   = "#103310" # palette accent color closest to foreground.
gray_scale_1       = "#ededed" # gray color closest to background.
gray_scale_2       = "#bbbbbb" # gray color intermediate to gray_scale_1 and gray_scale_3.
gray_scale_3       = "#707070" # intermediary color directly between gray_scale_1 (closest to background) and gray_scale_5 (closest to foreground).
gray_scale_4       = "#484848" # gray color intermediate to gray_scale_3 and gray_scale_5
gray_scale_5       = "#2e2e2e" # gray color closest to foreground.
alert              = "#a30000" # clearly distinct color that stands out against other background, foreground, cursor, selection, palette_accent, and gray_scale colors.  should be a variant shade of minor_alert color, yet closer to the foreground color than background color.
minor_alert        = "#ffdddd" # clearly distinct color that stands out against other background, foreground, cursor, selection, palette_accent, and gray_scale colors.  should be a variant shade of alert color, yet closer to the background color than foreground color.

[colors.wezterm]
ansi_final = "#a8b3a8"
bright_final = "#c2d1c2"

[colors.nvim]
lsp_inlay_hint = "#ffaa33"
lsp_bright = "#934e00"

[colors.starship]
default_style = "#4e7a1c"
